version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-app:latest
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]